-- Миграция: Создание начальной структуры таблиц

-- Основная таблица товаров с идентификатором, названием и изображением
CREATE TABLE product (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255) NOT NULL,
    picture_url VARCHAR(255)
);

-- Таблица информации о товарах с ценами (денормализация относительно product)
CREATE TABLE product_info (
    product_id  BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    price       DOUBLE PRECISION
);

-- Таблица заказов с идентификатором и статусом
CREATE TABLE orders (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    status      VARCHAR(255)
);

-- Таблица дат заказов (денормализация относительно orders)
CREATE TABLE orders_date (
    order_id    BIGINT       NOT NULL,
    status      VARCHAR(255),
    date_created DATE        DEFAULT CURRENT_DATE
);

-- Таблица связи заказов и товаров (многие ко многим)
CREATE TABLE order_product (
    quantity    INTEGER      NOT NULL,
    order_id    BIGINT       NOT NULL,
    product_id  BIGINT       NOT NULL
);
